Repository lion-packages/bundle, pull requests merged in 2024-03, with the labels that each got.

#30 Format has been corrected to display the available web routes
  composer.lock
  src/LionBundle/Commands/Lion/Route/RouteListCommand.php
Labels: bug

#31 Modified seed execution to run seeds
  src/LionBundle/Commands/Lion/DB/DBSeedCommand.php
Labels: enhancement

#32 EmptyMigrationsCommand added
  composer.lock
  src/LionBundle/Commands/Lion/DB/DBSeedCommand.php
  src/LionBundle/Commands/Lion/DB/ShowDatabasesCommand.php
  src/LionBundle/Commands/Lion/Migrations/EmptyMigrationsCommand.php
  src/LionBundle/Commands/Lion/Migrations/FreshMigrationsCommand.php
  src/LionBundle/Commands/Lion/New/NewMigrationCommand.php
  src/LionBundle/Commands/Lion/New/SeedCommand.php
  tests/Commands/Lion/Migrations/EmptyMigrationsCommandTest.php
  tests/Commands/Lion/Migrations/FreshMigrationsCommandTest.php
  tests/Commands/Lion/New/NewMigrationCommandTest.php
Labels: documentation, enhancement

#34 Integration for scheduled tasks
  .env.example
  src/LionBundle/Commands/Lion/New/CronCommand.php
  src/LionBundle/Commands/Lion/New/MigrationCommand.php
  src/LionBundle/Commands/Lion/Schedule/ListScheduleCommand.php
  src/LionBundle/Commands/Lion/Schedule/UpScheduleCommand.php
  src/LionBundle/Helpers/Commands/ClassFactory.php
  src/LionBundle/Helpers/Commands/Schedule/Schedule.php
  src/LionBundle/Interface/ScheduleInterface.php
  tests/Commands/Lion/Migrations/FreshMigrationsCommandTest.php
  tests/Commands/Lion/New/MigrationCommandTest.php
Labels: documentation, enhancement

#35 Fix when generating rules
  src/LionBundle/Commands/Lion/DB/RulesDBCommand.php
  src/LionBundle/Commands/Lion/New/CronCommand.php
  src/LionBundle/Commands/Lion/New/RulesCommand.php
  src/LionBundle/Commands/Lion/New/SocketCommand.php
  tests/Commands/Lion/DB/RulesDBCommandTest.php
  tests/Commands/Lion/New/SocketCommandTest.php
Labels: bug, documentation, enhancement

#36 Test support for scheduled tasks
  src/LionBundle/Commands/Lion/DB/CrudCommand.php
  src/LionBundle/Commands/Lion/New/CronCommand.php
  src/LionBundle/Commands/Lion/Schedule/ListScheduleCommand.php
  src/LionBundle/Commands/Lion/Schedule/UpScheduleCommand.php
  tests/Commands/Lion/New/CronCommandTest.php
  tests/Commands/Lion/Schedule/ListScheduleCommandTest.php
  tests/Commands/Lion/Schedule/UpScheduleCommandTest.php
Labels: bug, enhancement

#37 Fixed reading available sockets in ServerSocketCommand
  composer.lock
  src/LionBundle/Commands/Lion/Sockets/ServerSocketCommand.php
  tests/Commands/Lion/Sockets/ServerSocketCommandTest.php
Labels: bug

#38 Fixed CRON task injection in crontab service
  src/LionBundle/Commands/Lion/New/CapsuleCommand.php
  src/LionBundle/Commands/Lion/Schedule/UpScheduleCommand.php
Labels: bug

#41 Bug fixes in helpers and web route list
  composer.lock
  public/index.php
  routes/middleware.php
  routes/web.php
  src/LionBundle/Commands/Lion/Route/RouteListCommand.php
  src/LionBundle/Helpers/Bundle/helpers.php
  tests/Commands/Lion/Route/RouteListCommandTest.php
  tests/Helpers/Bundle/HelpersTest.php
Labels: bug, dependencies, tests

#42 Added validations for isSucces and isError helpers
  src/LionBundle/Helpers/Bundle/helpers.php
  tests/Helpers/Bundle/HelpersTest.php
Labels: enhancement

#43 Integration of Exceptions
  public/index.php
  src/LionBundle/Commands/Lion/New/AESCommand.php
  src/LionBundle/Commands/Lion/New/CronCommand.php
  src/LionBundle/Commands/Lion/New/EnumCommand.php
  src/LionBundle/Commands/Lion/New/ExceptionsCommand.php
  src/LionBundle/Commands/Lion/New/MigrationCommand.php
  src/LionBundle/Commands/Lion/New/RSACommand.php
  src/LionBundle/Commands/Lion/New/SHFileCommand.php
  src/LionBundle/Helpers/ExceptionCore.php
  tests/Commands/Lion/New/ExceptionsCommandTest.php
Labels: enhancement, dependencies

#44 Support and documentation has been extended when generating capsule classes
  Dockerfile
  src/LionBundle/Commands/Lion/New/CapsuleCommand.php
  src/LionBundle/Helpers/Commands/ClassFactory.php
  src/LionBundle/Interface/CapsuleInterface.php
Labels: enhancement

#45 Extended Project Structure Documentation
  src/LionBundle/Commands/CommandHandler.php
  src/LionBundle/Commands/Lion/DB/CrudCommand.php
  src/LionBundle/Commands/Lion/DB/DBSeedCommand.php
  src/LionBundle/Commands/Lion/DB/MySQL/DBCapsuleCommand.php
  src/LionBundle/Commands/Lion/DB/RulesDBCommand.php
  src/LionBundle/Commands/Lion/DB/ShowDatabasesCommand.php
  src/LionBundle/Commands/Lion/HashCommand.php
  src/LionBundle/Commands/Lion/InfoCommand.php
  src/LionBundle/Commands/Lion/Migrations/EmptyMigrationsCommand.php
  src/LionBundle/Commands/Lion/Migrations/FreshMigrationsCommand.php
  src/LionBundle/Commands/Lion/New/AESCommand.php
  src/LionBundle/Commands/Lion/New/CapsuleCommand.php
  src/LionBundle/Commands/Lion/New/CommandsCommand.php
  src/LionBundle/Commands/Lion/New/ControllerCommand.php
  src/LionBundle/Commands/Lion/New/CronCommand.php
  src/LionBundle/Commands/Lion/New/EnumCommand.php
  src/LionBundle/Commands/Lion/New/ExceptionsCommand.php
  src/LionBundle/Commands/Lion/New/FactoryCommand.php
  src/LionBundle/Commands/Lion/New/InterfaceCommand.php
  src/LionBundle/Commands/Lion/New/MiddlewareCommand.php
  src/LionBundle/Commands/Lion/New/MigrationCommand.php
  src/LionBundle/Commands/Lion/New/ModelCommand.php
  src/LionBundle/Commands/Lion/New/RSACommand.php
  src/LionBundle/Commands/Lion/New/RulesCommand.php
  src/LionBundle/Commands/Lion/New/SHFileCommand.php
  src/LionBundle/Commands/Lion/New/SeedCommand.php
  src/LionBundle/Commands/Lion/New/SocketCommand.php
  src/LionBundle/Commands/Lion/New/TestCommand.php
  src/LionBundle/Commands/Lion/New/TraitCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInitCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInstallCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmRunBuildCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmUninstallCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmUpdateCommand.php
  src/LionBundle/Commands/Lion/Route/PostmanCollectionCommand.php
  src/LionBundle/Commands/Lion/Route/RouteListCommand.php
  src/LionBundle/Commands/Lion/RunTestCommand.php
  src/LionBundle/Commands/Lion/Schedule/ListScheduleCommand.php
  src/LionBundle/Commands/Lion/Schedule/UpScheduleCommand.php
  src/LionBundle/Commands/Lion/ServerCommand.php
  src/LionBundle/Commands/Lion/Sockets/ServerSocketCommand.php
  src/LionBundle/Commands/Npm/NpmInitCommand.php
  src/LionBundle/Commands/Npm/NpmInstallCommand.php
  src/LionBundle/Commands/Npm/NpmRunBuildCommand.php
  src/LionBundle/Commands/Npm/NpmUninstallCommand.php
  src/LionBundle/Commands/Npm/NpmUpdateCommand.php
  src/LionBundle/Helpers/Commands/ClassCommandFactory.php
  src/LionBundle/Helpers/Commands/ClassFactory.php
  src/LionBundle/Helpers/Commands/Migrations/MigrationFactory.php
  src/LionBundle/Helpers/Commands/Schedule/Schedule.php
  src/LionBundle/Helpers/Commands/Selection/MenuCommand.php
Labels: documentation

#47 Generation of double rules for optional properties is validated
  src/LionBundle/Commands/Lion/DB/RulesDBCommand.php
  tests/Commands/Lion/DB/RulesDBCommandTest.php
Labels: enhancement, tests

#49 Dependencies are updated
  composer.lock
Labels: dependencies

#50 Command correction
  src/LionBundle/Commands/Lion/New/CapsuleCommand.php
  src/LionBundle/Commands/Lion/New/TestCommand.php
Labels: bug
