Repository lion-packages/bundle, pull requests merged in 2024-05, with the labels that each got.

#57 Support for local installation
  docker-compose.yml
  supervisord.conf
Labels: continuous integration

#58 Correct logger function call with incorrect data type
  composer.lock
  src/LionBundle/Helpers/Rules.php
Labels: bug

#59 Parameter error has been corrected to display rule errors
  src/LionBundle/Helpers/Rules.php
Labels: bug

#60 Command fix
  src/LionBundle/Commands/Lion/DB/CrudCommand.php
  src/LionBundle/Commands/Lion/DB/DBCapsuleCommand.php
  src/LionBundle/Commands/Lion/DB/DBSeedCommand.php
  src/LionBundle/Commands/Lion/Migrations/FreshMigrationsCommand.php
  src/LionBundle/Commands/Lion/New/SeedCommand.php
  src/LionBundle/Helpers/Commands/Migrations/MigrationFactory.php
  src/LionBundle/Interface/Migrations/StoreProcedureInterface.php
  src/LionBundle/Interface/Migrations/TableInterface.php
  src/LionBundle/Interface/Migrations/ViewInterface.php
  tests/Commands/Lion/DB/CrudCommandTest.php
  tests/Commands/Lion/DB/DBCapsuleCommandTest.php
  tests/Commands/Lion/Migrations/FreshMigrationsCommandTest.php
  tests/Helpers/Commands/Migrations/MigrationFactoryTest.php
Labels: bug, documentation, enhancement, refactor

#61 Rule Validation
  composer.json
  composer.lock
  phpunit.xml
  public/index.php
  routes/rules.php
  src/LionBundle/Commands/Lion/Migrations/FreshMigrationsCommand.php
  src/LionBundle/Commands/Lion/New/RulesCommand.php
  src/LionBundle/Enums/StatusResponseEnum.php
  src/LionBundle/Exceptions/RulesException.php
  src/LionBundle/Helpers/Rules.php
  src/LionBundle/Kernel/HttpKernel.php
  test.sh
  tests/Commands/Lion/New/RulesCommandTest.php
  tests/Enums/StatusResponseEnumTest.php
  tests/Exceptions/RulesExceptionTest.php
  tests/Helpers/Bundle/HelpersTest.php
  tests/Helpers/ExceptionCoreTest.php
  tests/Helpers/RulesTest.php
  tests/Kernel/HttpKernelTest.php
  tests/Providers/Kernel/HttpKernelProviderTrait.php
Labels: documentation, refactor, tests

#64 lion/exceptions v1.1.1 has been integrated
  composer.lock
  routes/web.php
Labels: dependencies

#65 Lion/exceptions v1.1.2 has been integrated
  composer.lock
Labels: dependencies

#66 Use of constants has been corrected
  src/LionBundle/Commands/Lion/DB/ShowDatabasesCommand.php
  src/LionBundle/Commands/Lion/New/AESCommand.php
  src/LionBundle/Commands/Lion/New/TraitCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInitCommand.php
  src/LionBundle/Commands/Lion/RunTestCommand.php
  src/LionBundle/Commands/Lion/Schedule/ScheduleSchemaCommand.php
  src/LionBundle/Helpers/Commands/Schedule/TaskQueue.php
  src/LionBundle/Helpers/FileWriter.php
  tests/Helpers/Bundle/HelpersTest.php
  tests/Helpers/Commands/PostmanCollectionTest.php
Labels: bug

#67 Extended testing support
  .gitignore
  Dockerfile
  composer.json
  composer.lock
  docker-compose.yml
  phpunit.xml
  routes/rules.php
  sockets/index.html
  src/LionBundle/Commands/Lion/RunTestCommand.php
  src/LionBundle/Helpers/Bundle/constants.php
  src/LionBundle/Helpers/Commands/ClassFactory.php
  src/LionBundle/Helpers/Commands/PostmanCollection.php
  src/LionBundle/Interface/SingletonInterface.php
  src/LionBundle/Traits/Singleton.php
  src/LionBundle/Traits/SingletonTrait.php
  supervisord.conf
  test-report.sh
  tests/Commands/Lion/Route/PostmanCollectionCommandTest.php
  tests/Commands/Lion/Route/RouteListCommandTest.php
  tests/Helpers/Bundle/ConstantsTest.php
  tests/Helpers/Bundle/HelpersTest.php
  tests/Helpers/Commands/ClassCommandFactoryTest.php
  tests/Helpers/Commands/ClassFactoryTest.php
  tests/Helpers/Commands/PostmanCollectionTest.php
  tests/Helpers/Commands/Schedule/TaskQueueTest.php
  tests/Helpers/Commands/Selection/MenuCommandTest.php
  tests/Helpers/EnvTest.php
  tests/Helpers/FileWriterTest.php
  tests/Kernel/HttpKernelTest.php
  tests/Providers/Helpers/ClassFactoryProviderTrait.php
  tests/Providers/Helpers/Commands/AddRoutesProvider.json
  tests/Providers/Helpers/Commands/GetRoutesProvider.json
  tests/Providers/Helpers/Commands/PostmanProvider.json
  tests/Providers/Helpers/Commands/RulesProvider.php
  tests/Providers/Helpers/EnvProviderTrait.php
  tests/Providers/Helpers/FileWriterProviderTrait.php
  tests/Providers/Helpers/HelpersProviderTrait.php
  tests/Providers/Helpers/PostmanCollectionProviderTrait.php
  tests/Providers/Traits/SingletonProvider.php
  tests/TestingTest.php
  tests/Traits/.gitignore
  tests/Traits/SingletonTraitTest.php
  tests/bootstrap.php
Labels: dependencies, tests, continuous integration

#68 Component refactoring
  composer.json
  composer.lock
  phpunit.xml
  src/LionBundle/Commands/Lion/New/CommandsCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmRunDevCommand.php
  src/LionBundle/Commands/Lion/RunTestCommand.php
  src/LionBundle/Commands/Lion/Schedule/ListScheduleCommand.php
  src/LionBundle/Commands/Lion/Schedule/RunQueuedTasksCommand.php
  src/LionBundle/Commands/Lion/Schedule/ScheduleSchemaCommand.php
  src/LionBundle/Commands/Npm/NpmRunDevCommand.php
  src/LionBundle/Helpers/Commands/ProcessCommand.php
  src/LionBundle/Helpers/Commands/Selection/MenuCommand.php
  tests/Commands/Lion/New/AESTest.php
  tests/Commands/Lion/Schedule/RunQueuedTasksCommandTest.php
  tests/Commands/Lion/Schedule/ScheduleSchemaCommandTest.php
  tests/Helpers/Commands/ProcessCommandTest.php
  tests/Helpers/Commands/Schedule/TaskQueueTest.php
  tests/Helpers/Commands/Selection/MenuCommandTest.php
  tests/Providers/Commands/TaskQueueSchemaProviderTrait.php
Labels: documentation, enhancement, refactor, tests

#69 Helper request has been added to capture data sent through HTTP requests
  src/LionBundle/Commands/Lion/New/CapsuleCommand.php
  src/LionBundle/Helpers/Bundle/helpers.php
  tests/Helpers/Bundle/HelpersTest.php
  tests/Providers/Helpers/HelpersProviderTrait.php
Labels: enhancement

#70 Support and Maintenance
  composer.json
  composer.lock
  phpunit.xml
  src/LionBundle/Enums/TaskStatusEnum.php
  src/LionBundle/Exceptions/MiddlewareException.php
  src/LionBundle/Helpers/Bundle/helpers.php
  src/LionBundle/Helpers/Commands/Schedule/TaskQueue.php
  src/LionBundle/Helpers/Commands/Selection/MenuCommand.php
  src/LionBundle/Kernel/HttpKernel.php
  src/LionBundle/Middleware/RouteMiddleware.php
  tests/Commands/Lion/New/ExceptionsCommandTest.php
  tests/Exceptions/MiddlewareExceptionTest.php
  tests/Exceptions/RulesExceptionTest.php
  tests/Helpers/Bundle/HelpersTest.php
  tests/Helpers/Commands/PostmanCollectionTest.php
  tests/Helpers/Commands/Schedule/TaskQueueTest.php
  tests/Helpers/Commands/Selection/MenuCommandTest.php
  tests/Kernel/HttpKernelTest.php
  tests/Middleware/RouteMiddlewareTest.php
Labels: dependencies

#71 Aes support has been extended to new:aes
  src/LionBundle/Commands/Lion/New/AESCommand.php
Labels: enhancement

#72 Command fix
  routes/web.php
  src/LionBundle/Commands/Lion/New/CommandsCommand.php
  src/LionBundle/Commands/Lion/New/EnumCommand.php
  src/LionBundle/Commands/Lion/New/MiddlewareCommand.php
  src/LionBundle/Commands/Lion/New/SeedCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInitCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInstallCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmRunBuildCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmUninstallCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmUpdateCommand.php
  src/LionBundle/Helpers/Commands/PostmanCollection.php
  tests/Commands/Lion/Npm/NpmInstallCommandTest.php
  tests/Commands/Lion/Npm/NpmRunBuildCommandTest.php
  tests/Commands/Lion/Npm/NpmUninstallCommandTest.php
Labels: bug, refactor, tests

#73 Documentation
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  phpunit.xml
Labels: documentation
