Repository lion-packages/bundle, pull requests merged in 2024-02, with the labels that each got.

#16 command file extension has been validated
  lion
  npm
  src/LionBundle/Commands/CommandHandler.php
Labels: bug

#17 migration classes have been validated when refreshing
  src/LionBundle/Commands/Lion/Migrations/FreshMigrationsCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInstallCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmUninstallCommand.php
  src/LionBundle/Helpers/Commands/Migrations/MigrationFactory.php
Labels: bug

#18 Command corrections and validations
  composer.lock
  docker-compose.yml
  src/LionBundle/Commands/Lion/DB/CrudCommand.php
  src/LionBundle/Commands/Lion/DB/MySQL/DBCapsuleCommand.php
  src/LionBundle/Commands/Lion/DB/MySQL/DBCapsulesCommand.php
  src/LionBundle/Commands/Lion/DB/RulesDBCommand.php
  src/LionBundle/Commands/Lion/Migrations/NewMigrationCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInitCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInstallCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmRunBuildCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmUninstallCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmUpdateCommand.php
  src/LionBundle/Helpers/Commands/SelectedDatabaseConnection.php
  src/LionBundle/Helpers/Commands/Selection/MenuCommand.php
  test.sh
  tests/Commands/Lion/DB/MySQL/DBCapsuleCommandTest.php
  tests/Commands/Lion/DB/MySQL/DBCapsulesCommandTest.php
Labels: bug

#19 Error correction
  .env.example
  .gitignore
  lion
  npm
  routes/web.php
  src/LionBundle/Commands/Lion/DB/CrudCommand.php
  src/LionBundle/Commands/Lion/DB/MySQL/DBCapsuleCommand.php
  src/LionBundle/Commands/Lion/DB/MySQL/DBCapsulesCommand.php
  src/LionBundle/Commands/Lion/DB/RulesDBCommand.php
  src/LionBundle/Commands/Lion/New/CapsuleCommand.php
  src/LionBundle/Commands/Lion/Route/PostmanCollectionCommand.php
  src/LionBundle/Helpers/Commands/ClassFactory.php
  src/LionBundle/Helpers/Commands/PostmanCollection.php
  tests/Commands/Lion/New/CapsuleCommandTest.php
  tests/Commands/Lion/Route/PostmanCollectionCommandTest.php
  tests/Providers/PostmanProvider.json
Labels: bug

#21 Command correction
  composer.json
  composer.lock
  lion
  public/index.php
  routes/middleware.php
  routes/web.php
  src/LionBundle/Commands/Lion/Route/RouteListCommand.php
  src/LionBundle/Helpers/Commands/PostmanCollection.php
  src/LionBundle/HttpKernel.php
  tests/Commands/Lion/Route/PostmanCollectionCommandTest.php
  tests/Commands/Lion/Route/RouteListCommandTest.php
  tests/Providers/PostmanProvider.json
Labels: bug

#22 Update to modify migration bodies
  composer.lock
  src/LionBundle/Commands/Lion/Migrations/NewMigrationCommand.php
  src/LionBundle/Commands/Lion/New/MiddlewareCommand.php
  src/LionBundle/Helpers/Commands/Migrations/MigrationFactory.php
  src/LionBundle/Traits/Migration.php
Labels: enhancement

#23 migration generation has been fixed
  .env.example
  composer.lock
  docker-compose.yml
  src/LionBundle/Helpers/Commands/Migrations/MigrationFactory.php
  test.sh
  tests/Commands/Lion/Migrations/NewMigrationCommandTest.php
  tests/MailhogTest.php
  tests/Providers/ConnectionProviderTrait.php
  tests/Providers/EmailProviderTrait.php
Labels: bug

#25 Container configuration correction for environment variables
  .env.example
  Dockerfile
  composer.json
  docker-compose.yml
  lion
  npm
  phpunit.xml
  routes/web.php
  src/LionBundle/Commands/Lion/HashCommand.php
  src/LionBundle/Commands/Lion/New/SHFileCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInitCommand.php
  src/LionBundle/Commands/Lion/Route/PostmanCollectionCommand.php
  src/LionBundle/Commands/Lion/Route/RouteListCommand.php
  src/LionBundle/Helpers/Bundle/constans.php
  src/LionBundle/Helpers/RedisClient.php
  src/LionBundle/Middleware/RouteMiddleware.php
  test.sh
  tests/Commands/Lion/SH/SHFileCommandTest.php
  tests/Helpers/Bundle/HelpersTest.php
  tests/Helpers/RedisClientTest.php
  tests/MailhogTest.php
  tests/Providers/ConnectionProviderTrait.php
  tests/Providers/EmailProviderTrait.php
  tests/RedisConnectionTest.php
Labels: bug, enhancement

#26 Correction of routes for different systems
  composer.lock
  src/LionBundle/Commands/CommandHandler.php
  src/LionBundle/Commands/Lion/DB/MySQL/FactoryCommand.php
  src/LionBundle/Commands/Lion/DB/Seed/NewSeedCommand.php
  src/LionBundle/Commands/Lion/DB/Seed/RunSeedCommand.php
  src/LionBundle/Commands/Lion/Migrations/FreshMigrationsCommand.php
  src/LionBundle/Commands/Lion/New/RulesCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInitCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInstallCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmRunBuildCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmUninstallCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmUpdateCommand.php
  src/LionBundle/Commands/Lion/RSA/NewRSACommand.php
  src/LionBundle/Commands/Lion/RunTestCommand.php
  src/LionBundle/Helpers/Commands/ClassFactory.php
  src/LionBundle/Helpers/Commands/Selection/MenuCommand.php
  src/LionBundle/Helpers/FileWriter.php
  src/LionBundle/Interface/CapsuleInterface.php
  src/LionBundle/Interface/FactoryInterface.php
  src/LionBundle/Interface/MigrationUpInterface.php
  src/LionBundle/Interface/SeedInterface.php
Labels: bug, documentation, enhancement

#27 Fixed vite command initialization to create projects
  src/LionBundle/Commands/Lion/Npm/NpmInitCommand.php
  src/LionBundle/Traits/Http.php
Labels: bug

#28 Electron-vite project integration
  Dockerfile
  docker-compose.yml
  lion
  npm
  src/LionBundle/Commands/CommandHandler.php
  src/LionBundle/Commands/Lion/AES/NewAESCommand.php
  src/LionBundle/Commands/Lion/Migrations/FreshMigrationsCommand.php
  src/LionBundle/Commands/Lion/New/AESCommand.php
  src/LionBundle/Commands/Lion/New/RSACommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInitCommand.php
  src/LionBundle/Helpers/Commands/Selection/MenuCommand.php
  src/LionBundle/Middleware/RouteMiddleware.php
  src/LionBundle/Traits/AES.php
  tests/Commands/Lion/New/AESTest.php
  tests/Commands/Lion/New/RSACommandTest.php
  tests/Commands/Lion/Npm/NpmInitCommandTest.php
Labels: documentation, enhancement

#29 Seed commands relocated
  src/LionBundle/Commands/Lion/DB/DBSeedCommand.php
  src/LionBundle/Commands/Lion/New/FactoryCommand.php
  src/LionBundle/Commands/Lion/New/SeedCommand.php
  tests/Commands/Lion/DB/DBSeedCommandTest.php
  tests/Commands/Lion/DB/FactoryCommandTest.php
  tests/Commands/Lion/New/SeedCommandTest.php
Labels: enhancement
