Repository lion-packages/bundle, pull requests merged in 2025-03, with the labels that each got.

#129 Handling tables modified by databases in migrations
  .env.actions
  .env.example
  composer.json
  lion
  npm
  src/LionBundle/Commands/Lion/DB/ShowDatabasesCommand.php
  src/LionBundle/Commands/Lion/Migrations/EmptyMigrationsCommand.php
  src/LionBundle/Commands/Lion/Migrations/FreshMigrationsCommand.php
  src/LionBundle/Commands/Lion/New/MigrationCommand.php
  src/LionBundle/Helpers/Commands/Migrations/MigrationFactory.php
  src/LionBundle/Helpers/Commands/Migrations/Migrations.php
  src/LionBundle/Interface/Migrations/StoredProcedureInterface.php
  tests/Commands/Lion/DB/ShowDatabasesCommandTest.php
  tests/Commands/Lion/Migrations/EmptyMigrationsCommandTest.php
  tests/Commands/Lion/Migrations/FreshMigrationsCommandTest.php
  tests/Commands/Lion/New/MigrationCommandTest.php
  tests/Helpers/Commands/Migrations/MigrationFactoryTest.php
  tests/Helpers/Commands/Migrations/MigrationsTest.php
  tests/Providers/Helpers/Commands/MigrationsFactoryProviderTrait.php
  tests/bootstrap.php
  tests/lion_database.sqlite
Labels: enhancement, dependencies, refactor, tests

#130 Validations added to order migrations and seeds
  lion_database.sqlite
  src/LionBundle/Helpers/Commands/Migrations/Migrations.php
Labels: enhancement

#131 Remove UpScheduleCommand, ListScheduleCommand and CronCommand
  lion_database.sqlite
  src/LionBundle/Commands/Lion/New/CronCommand.php
  src/LionBundle/Commands/Lion/Route/RouteListCommand.php
  src/LionBundle/Commands/Lion/Schedule/ListScheduleCommand.php
  src/LionBundle/Commands/Lion/Schedule/UpScheduleCommand.php
  src/LionBundle/Helpers/Commands/Migrations/Migrations.php
  src/LionBundle/Helpers/Commands/Schedule/Schedule.php
  src/LionBundle/Helpers/Commands/Schedule/Task.php
  src/LionBundle/Helpers/Commands/Schedule/TaskQueue.php
  src/LionBundle/Interface/ScheduleInterface.php
  tests/Commands/Lion/New/CronCommandTest.php
  tests/Commands/Lion/Schedule/ListScheduleCommandTest.php
  tests/Commands/Lion/Schedule/UpScheduleCommandTest.php
  tests/Helpers/Commands/Schedule/ScheduleTest.php
  tests/Helpers/Commands/Schedule/TaskQueueTest.php
Labels: enhancement

#133 Modifying the body of capsule classes
  composer.json
  src/LionBundle/Commands/Lion/DB/ShowDatabasesCommand.php
  src/LionBundle/Commands/Lion/New/CapsuleCommand.php
  src/LionBundle/Commands/Lion/New/HtmlCommand.php
  src/LionBundle/Helpers/Commands/Capsule/CapsuleFactory.php
  src/LionBundle/Helpers/Commands/Html.php
  tests/Helpers/Commands/Capsule/CapsuleFactoryTest.php
  tests/Helpers/Commands/HtmlTest.php
  tests/Providers/Helpers/Commands/HtmlTemplate.html
Labels: enhancement

#134 The body of the Controller and Models classes is modified
  src/LionBundle/Commands/Lion/New/ControllerCommand.php
  src/LionBundle/Commands/Lion/New/ModelCommand.php
  src/LionBundle/Helpers/Commands/ClassFactory.php
  tests/Providers/Helpers/ClassFactoryProviderTrait.php
Labels: enhancement

#135 The body of the Controller and Model classes is modified when generating CRUD
  .gitignore
  composer.json
  phpunit.xml
  src/LionBundle/Commands/Lion/DB/CrudCommand.php
Labels: enhancement

#136 Added validation to generate CRUD with SQLite
  .gitignore
  phpunit.xml
  src/LionBundle/Commands/Lion/DB/CrudCommand.php
Labels: enhancement

#138 PSR-12 and PHPStan standardization changes are added
  src/LionBundle/Helpers/Bundle/helpers.php
Labels: standardization

#137 Add cache in workflow
  .github/workflows/php.yml
Labels: continuous integration
