Repository lion-packages/bundle, pull requests merged in 2025-04, with the labels that each got.

#139 Integrate Dependency-Review
  .github/workflows/php.yml
Labels: continuous integration

#140 Integrate PHPLint
  .github/workflows/php.yml
  .gitignore
  composer.json
Labels: continuous integration

#141 Add Dependabot configuration
  .github/dependabot.yml
Labels: continuous integration

#143 Fixed implementation of the lion/command execution method
  src/LionBundle/Commands/Lion/Npm/NpmInitCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInstallCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmRunBuildCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmUninstallCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmUpdateCommand.php
  tests/Commands/Lion/Npm/NpmInstallCommandTest.php
  tests/Commands/Lion/Npm/NpmRunBuildCommandTest.php
  tests/Commands/Lion/Npm/NpmUninstallCommandTest.php
  tests/Commands/Lion/Npm/NpmUpdateCommandTest.php
Labels: bug, tests

#142 Update README.md
  .github/README.md
Labels: documentation

#144 Update README.md
  .github/README.md
Labels: documentation

#145 Interface for middleware is implemented
  src/LionBundle/Middleware/HttpsMiddleware.php
  tests/Middleware/HttpsMiddlewareTest.php
Labels: enhancement

#146 Html class is added as support
  src/LionBundle/Commands/Lion/New/HtmlCommand.php
  src/LionBundle/Support/Html.php
  tests/Commands/Lion/New/HtmlCommandTest.php
  tests/Support/HtmlTest.php
Labels: enhancement, tests

#148 Fetch class is added as support
  .gitignore
  src/LionBundle/Commands/Lion/Route/PostmanCollectionCommand.php
  src/LionBundle/Commands/Lion/Route/RouteListCommand.php
  src/LionBundle/Helpers/Bundle/helpers.php
  src/LionBundle/Support/Http/Fetch.php
  src/LionBundle/Support/Http/FetchConfiguration.php
  tests/Helpers/Bundle/HelpersTest.php
  tests/Helpers/Commands/PostmanCollectionTest.php
  tests/Support/Http/FetchConfigurationTest.php
  tests/Support/Http/FetchTest.php
Labels: enhancement, tests

#149 Routes class is added as support
  routes/middleware.php
  routes/web.php
  src/LionBundle/Commands/Lion/Route/RouteListCommand.php
  src/LionBundle/Support/Http/Routes.php
  tests/Commands/Lion/Route/RouteListCommandTest.php
  tests/Support/Http/RoutesTest.php
Labels: enhancement, tests

#150 Redis usage is replaced by Predis Client
  routes/web.php
  src/LionBundle/Commands/Lion/Schedule/RunQueuedTasksCommand.php
  src/LionBundle/Helpers/Commands/Schedule/TaskQueue.php
  tests/Commands/Lion/Schedule/RunQueuedTasksCommandTest.php
  tests/Helpers/Commands/Schedule/TaskQueueTest.php
Labels: refactor, tests

#151 Redis class is removed
  src/LionBundle/Support/Redis.php
  tests/Support/RedisTest.php
Labels: enhancement

#152 The env wizard is used to generate keys with RSA
  src/LionBundle/Commands/Lion/New/RSACommand.php
Labels: enhancement

#153 Added parent method initialization (initialize) in RunQueuedTasksCommand
  src/LionBundle/Commands/Lion/Schedule/RunQueuedTasksCommand.php
Labels: enhancement

#155 HTTPS Configuration for Docker and Github Actions
  .env.actions
  .env.example
  .github/workflows/php.yml
  Dockerfile
  docker-compose.yml
  src/LionBundle/Commands/Lion/Route/PostmanCollectionCommand.php
  storage/logs/.gitignore
  supervisord.conf
  tests/Helpers/Commands/PostmanCollectionTest.php
  tests/Providers/Helpers/Commands/AddRoutesProvider.json
  tests/Providers/Helpers/Commands/PostmanProvider.json
  tests/Providers/Helpers/EnvProviderTrait.php
  tests/Providers/Helpers/HelpersProviderTrait.php
Labels: enhancement, tests, continuous integration

#156 Environment variables are updated for local
  .env.example
Labels: enhancement

#157 Fix error when selecting a front-end project
  src/LionBundle/Helpers/Commands/Selection/MenuCommand.php
  tests/Helpers/Commands/Selection/MenuCommandTest.php
Labels: bug

#158 Update dependabot.yml
  .github/dependabot.yml
Labels: continuous integration

#159 Apply fixes from StyleCI
  src/LionBundle/Commands/Lion/DB/ShowDatabasesCommand.php
  src/LionBundle/Traits/SingletonTrait.php
  tests/Exceptions/MiddlewareExceptionTest.php
  tests/Helpers/Commands/Selection/MenuCommandTest.php
  tests/Providers/Helpers/PostmanCollectionProviderTrait.php
Labels: standardization

#160 Added StyleCI configuration
  .styleci.yml
  src/LionBundle/Commands/Lion/DB/ShowDatabasesCommand.php
  tests/Exceptions/MiddlewareExceptionTest.php
  tests/Helpers/Commands/Selection/MenuCommandTest.php
  tests/Providers/Helpers/PostmanCollectionProviderTrait.php
Labels: continuous integration

#161 Adding a condition to run test coverage in Github Actions (Pull Request)
  .github/workflows/php.yml
Labels: continuous integration

#162 Define the execution time for Github Actions
  .github/workflows/php.yml
Labels: continuous integration

#163 Define the runtime for the Dependabot
  .github/dependabot.yml
Labels: continuous integration

#164 The composer settings are updated
  composer.json
Labels: dependencies

#167 Conditions for creating Task objects are removed.
  src/LionBundle/Commands/Lion/Schedule/RunQueuedTasksCommand.php
  src/LionBundle/Helpers/Commands/Schedule/Task.php
  tests/Helpers/Commands/Schedule/TaskTest.php
Labels: enhancement, tests

#168 Task class added to Support
  src/LionBundle/Helpers/Commands/Schedule/TaskQueue.php
  src/LionBundle/Support/Task.php
  tests/Helpers/Commands/Schedule/TaskQueueTest.php
  tests/Support/TaskTest.php
Labels: enhancement

#169 Support for adding multiple tasks to the queue
  src/LionBundle/Helpers/Commands/Schedule/TaskQueue.php
  tests/Helpers/Commands/Schedule/TaskQueueTest.php
Labels: enhancement, tests

#170 Added support for serializing exceptions in JSON format
  public/index.php
  src/LionBundle/Support/ExceptionHandler.php
  tests/Support/ExceptionHandlerTest.php
Labels: enhancement, tests
