Repository lion-packages/bundle, pull requests merged in 2025-02, with the labels that each got.

#113 Added integration to create projects with Astro
  .github/workflows/php.yml
  composer.json
  docker-compose.yml
  src/LionBundle/Commands/Lion/Migrations/FreshMigrationsCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInitCommand.php
  src/LionBundle/Helpers/Commands/Selection/MenuCommand.php
  tests/Commands/Lion/Npm/NpmInitCommandTest.php
  tests/Commands/Lion/Npm/NpmInstallCommandTest.php
  tests/Helpers/Commands/Selection/MenuCommandTest.php
Labels: enhancement, dependencies

#116 Ignored files
  .github/CODE_OF_CONDUCT.md
  test-report.sh
  test.sh
Labels: documentation

#115 Standardization with PHPStan and PHP_CodeSniffer is added
  phpunit.xml
  src/LionBundle/Commands/Lion/New/ModelCommand.php
  src/LionBundle/Commands/Lion/New/RSACommand.php
  src/LionBundle/Commands/Lion/New/RulesCommand.php
  src/LionBundle/Commands/Lion/New/SHFileCommand.php
  src/LionBundle/Commands/Lion/New/SeedCommand.php
  src/LionBundle/Commands/Lion/New/ServiceCommand.php
  src/LionBundle/Commands/Lion/New/SocketCommand.php
  src/LionBundle/Commands/Lion/New/TestCommand.php
  src/LionBundle/Commands/Lion/New/TraitCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInitCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInstallCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmRunDevCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmUninstallCommand.php
  src/LionBundle/Commands/Lion/Route/PostmanCollectionCommand.php
  src/LionBundle/Commands/Lion/Route/RouteListCommand.php
  src/LionBundle/Commands/Lion/RunTestCommand.php
  src/LionBundle/Commands/Lion/Schedule/ListScheduleCommand.php
  src/LionBundle/Commands/Lion/Schedule/RunQueuedTasksCommand.php
  src/LionBundle/Commands/Lion/Schedule/UpScheduleCommand.php
  src/LionBundle/Commands/Lion/ServerCommand.php
  src/LionBundle/Commands/Lion/Sockets/ServerSocketCommand.php
  src/LionBundle/Helpers/Bundle/constants.php
  src/LionBundle/Helpers/Bundle/helpers.php
  src/LionBundle/Helpers/Commands/ClassCommandFactory.php
  src/LionBundle/Helpers/Commands/ClassFactory.php
  src/LionBundle/Helpers/Commands/ComposerFactory.php
  src/LionBundle/Helpers/Commands/Migrations/Migrations.php
  src/LionBundle/Helpers/Commands/Selection/MenuCommand.php
  src/LionBundle/Test/Test.php
  tests/Commands/Lion/New/ModelCommandTest.php
  tests/Commands/Lion/New/RSACommandTest.php
  tests/Commands/Lion/New/RulesCommandTest.php
  tests/Commands/Lion/New/SeedCommandTest.php
  tests/Commands/Lion/New/ServiceCommandTest.php
  tests/Commands/Lion/New/SocketCommandTest.php
  tests/Commands/Lion/New/TestCommandTest.php
  tests/Commands/Lion/New/TraitCommandTest.php
  tests/Commands/Lion/Npm/NpmInitCommandTest.php
  tests/Commands/Lion/Npm/NpmUninstallCommandTest.php
  tests/Commands/Lion/Route/PostmanCollectionCommandTest.php
  tests/Commands/Lion/Route/RouteListCommandTest.php
  tests/Commands/Lion/SH/SHFileCommandTest.php
  tests/Commands/Lion/Schedule/ListScheduleCommandTest.php
  tests/Commands/Lion/Schedule/RunQueuedTasksCommandTest.php
  tests/Commands/Lion/Schedule/UpScheduleCommandTest.php
  tests/Helpers/Bundle/HelpersTest.php
  tests/Helpers/Commands/ComposerFactoryTest.php
  tests/Helpers/Commands/Migrations/MigrationsTest.php
  tests/Helpers/Commands/Selection/MenuCommandTest.php
  tests/bootstrap.php
Labels: tests, standardization

#117 Standardization with PHPStan and PHP_CodeSniffer is added
  src/LionBundle/Commands/Lion/DB/ShowDatabasesCommand.php
  src/LionBundle/Commands/Lion/InfoCommand.php
  src/LionBundle/Commands/Lion/New/ClassCommand.php
  src/LionBundle/Commands/Lion/New/CommandsCommand.php
  src/LionBundle/Commands/Lion/New/ControllerCommand.php
  src/LionBundle/Commands/Lion/New/CronCommand.php
  src/LionBundle/Commands/Lion/New/EnumCommand.php
  src/LionBundle/Commands/Lion/New/ExceptionsCommand.php
  src/LionBundle/Commands/Lion/New/FactoryCommand.php
  src/LionBundle/Commands/Lion/New/HtmlCommand.php
  src/LionBundle/Commands/Lion/New/InterfaceCommand.php
  src/LionBundle/Commands/Lion/New/MiddlewareCommand.php
  src/LionBundle/Commands/Lion/New/MigrationCommand.php
  tests/Commands/Lion/DB/ShowDatabasesCommandTest.php
  tests/Commands/Lion/InfoCommandTest.php
  tests/Commands/Lion/New/ClassCommandTest.php
  tests/Commands/Lion/New/CommandsCommandTest.php
  tests/Commands/Lion/New/ControllerCommandTest.php
  tests/Commands/Lion/New/CronCommandTest.php
  tests/Commands/Lion/New/EnumCommandTest.php
  tests/Commands/Lion/New/ExceptionsCommandTest.php
  tests/Commands/Lion/New/FactoryCommandTest.php
  tests/Commands/Lion/New/HtmlCommandTest.php
  tests/Commands/Lion/New/InterfaceCommandTest.php
  tests/Commands/Lion/New/MiddlewareCommandTest.php
  tests/Commands/Lion/New/MigrationCommandTest.php
Labels: tests, standardization

#118 Standardization with PHPStan and PHP_CodeSniffer is added
  src/LionBundle/Commands/Lion/DB/DBCapsuleCommand.php
  src/LionBundle/Commands/Lion/DB/DBSeedCommand.php
  src/LionBundle/Commands/Lion/DB/RulesDBCommand.php
  src/LionBundle/Commands/Lion/Migrations/EmptyMigrationsCommand.php
  src/LionBundle/Commands/Lion/Migrations/FreshMigrationsCommand.php
  src/LionBundle/Commands/Lion/New/AESCommand.php
  src/LionBundle/Commands/Lion/New/CapsuleCommand.php
  tests/Commands/Lion/DB/DBCapsuleCommandTest.php
  tests/Commands/Lion/DB/DBSeedCommandTest.php
  tests/Commands/Lion/DB/RulesDBCommandTest.php
  tests/Commands/Lion/Migrations/EmptyMigrationsCommandTest.php
  tests/Commands/Lion/Migrations/FreshMigrationsCommandTest.php
  tests/Commands/Lion/New/AESTest.php
  tests/Commands/Lion/New/CapsuleCommandTest.php
Labels: tests, standardization

#119 Standardization with PHPStan and PHP_CodeSniffer is added
  .github/workflows/php.yml
  .gitignore
  src/LionBundle/Commands/CommandHandler.php
  src/LionBundle/Commands/Lion/DB/CrudCommand.php
  tests/Commands/Lion/DB/CrudCommandTest.php
Labels: tests, continuous integration, standardization

#120 Dependencies have been updated (lion/database v11.4.0)
  composer.json
Labels: dependencies

#121 A condition in RunTestCommand is corrected
  .env.example
  src/LionBundle/Commands/Lion/RunTestCommand.php
Labels: bug

#122 Validation is fixed to generate test coverage reports
  src/LionBundle/Commands/Lion/RunTestCommand.php
Labels: bug

#123 Dependencies have been updated (lion/database v11.5.2)
  composer.json
  src/LionBundle/Commands/Lion/DB/DBCapsuleCommand.php
  src/LionBundle/Helpers/Commands/Selection/MenuCommand.php
Labels: dependencies

#125 Dependencies have been updated (lion/database v11.6.1)
  composer.json
Labels: dependencies

#126 dependencies have been updated (lion/route v12.3.0)
  composer.json
  routes/middleware.php
  src/LionBundle/Commands/Lion/New/MiddlewareCommand.php
  src/LionBundle/Commands/Lion/Route/RouteListCommand.php
  src/LionBundle/Helpers/Http/Routes.php
  src/LionBundle/Middleware/RouteMiddleware.php
  tests/Commands/Lion/Route/RouteListCommandTest.php
  tests/Helpers/Http/RoutesTest.php
  tests/Middleware/RouteMiddlewareTest.php
Labels: dependencies, refactor, tests

#127 Dependencies have been updated (lion/database v11.7.0)
  composer.json
  src/LionBundle/Commands/Lion/Migrations/EmptyMigrationsCommand.php
  src/LionBundle/Commands/Lion/New/CapsuleCommand.php
  src/LionBundle/Traits/CapsuleTrait.php
Labels: enhancement, dependencies

#128 Annotations for methods generated in Controllers and Models are modified
  src/LionBundle/Commands/Lion/New/ControllerCommand.php
  src/LionBundle/Commands/Lion/New/ModelCommand.php
  src/LionBundle/Helpers/Commands/ClassFactory.php
  tests/Helpers/Commands/ClassFactoryTest.php
  tests/Providers/Helpers/ClassFactoryProviderTrait.php
Labels: enhancement
