Repository lion-packages/bundle, pull requests merged in 2025-01, with the labels that each got.

#109 Documentation files are relocated
  .github/CHANGELOG.md
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/README.md
Labels: documentation

#110 Dependencies have been updated (lion/database v11.2.0)
  composer.json
Labels: dependencies

#111 Installation path for Vite projects has been modified
  composer.json
  src/LionBundle/Commands/Lion/Npm/NpmInitCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmInstallCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmRunBuildCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmRunDevCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmRunTestCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmUninstallCommand.php
  src/LionBundle/Commands/Lion/Npm/NpmUpdateCommand.php
  src/LionBundle/Helpers/Commands/Selection/MenuCommand.php
  tests/Commands/Lion/Npm/NpmInitCommandTest.php
  tests/Commands/Lion/Npm/NpmInstallCommandTest.php
  tests/Commands/Lion/Npm/NpmRunBuildCommandTest.php
  tests/Commands/Lion/Npm/NpmUninstallCommandTest.php
  tests/Commands/Lion/Npm/NpmUpdateCommandTest.php
  tests/Helpers/Commands/Selection/MenuCommandTest.php
Labels: dependencies, refactor

#112 Update LICENSE
  LICENSE
Labels: documentation
